CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" int NOT NULL,
  "email" varchar(25) UNIQUE NOT NULL,
  "password" varchar(25) NOT NULL,
  "age" int NOT NULL,
  "rol" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "url" varchar(25) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(25) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" varchar(25) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(25) NOT NULL
);

CREATE TABLE "title" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL
);

CREATE TABLE "description" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(50) NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacher" varchar(25) NOT NULL
);

CREATE TABLE "name" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "age" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "age" int NOT NULL
);

CREATE TABLE "course_general" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_description" int NOT NULL,
  "course_level" int NOT NULL,
  "course_teacher" int NOT NULL,
  "course_user" int NOT NULL,
  "course_category" int NOT NULL,
  "course_videos" int NOT NULL,
  "course_title" int NOT NULL
);

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_level") REFERENCES "level" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_teacher") REFERENCES "teacher" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_title") REFERENCES "title" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_videos") REFERENCES "course_videos" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_category") REFERENCES "categories" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_description") REFERENCES "description" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_user") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("rol") REFERENCES "roles" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("name") REFERENCES "name" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("age") REFERENCES "age" ("id");


datos_entregable=# INSERT INTO name (name) VALUES ('Gerson'), ('Maria'), ('Marcos'), ('Javier');
INSERT 0 4
datos_entregable=# SELECT * FROM name;
 id |  name
----+--------
  1 | Gerson
  2 | Maria
  3 | Marcos
  4 | Javier
(4 filas)


datos_entregable=# INSERT INTO age (age) VALUES (18) , (21) , (30) , (35);
INSERT 0 4
datos_entregable=# SELECT * FROM age;
 id | age
----+-----
  1 |  18
  2 |  21
  3 |  30
  4 |  35
(4 filas)


datos_entregable=# INSERT INTO roles (rol) VALUES ('Student') , ('Teacher') , ('Admi');
INSERT 0 3
datos_entregable=# SELECT * FROM roles;
 id |   rol
----+---------
  1 | Student
  2 | Teacher
  3 | Admi
(3 filas)


datos_entregable=# INSERT INTO users (name , email , password , age , rol) VALUES
datos_entregable-# (1 , 'Gerson@gmail.com' , 'gerson456' , 2 , 1),
datos_entregable-# (2 , 'Maria@gmail.com' , 'maria334' , 3 , 2),
datos_entregable-# (3 , 'Marco@gmail.com' , 'marco678' , 4 , 3),
datos_entregable-# (4 , 'Javier@gmail.com' , 'javier788' , 1, 1);
INSERT 0 4
datos_entregable=# SELECT * FROM users;
 id | name |      email       | password  | age | rol
----+------+------------------+-----------+-----+-----
  1 |    1 | Gerson@gmail.com | gerson456 |   2 |   1
  2 |    2 | Maria@gmail.com  | maria334  |   3 |   2
  3 |    3 | Marco@gmail.com  | marco678  |   4 |   3
  4 |    4 | Javier@gmail.com | javier788 |   1 |   1
(4 filas)


postgres=# \c datos_entregable;
Ahora está conectado a la base de datos «datos_entregable» con el usuario «postgres».
datos_entregable=# INSERT INTO level (level) VALUES
datos_entregable-# ('Beginner'),
datos_entregable-# ('Intermediate'),
datos_entregable-# ('Advance');
INSERT 0 3
datos_entregable=# SELECT * FROM level;
 id |    level
----+--------------
  1 | Beginner
  2 | Intermediate
  3 | Advance
(3 filas)


datos_entregable=# INSERT INTO teacher (teacher) VALUES
datos_entregable-# ('Maria'),
datos_entregable-# ('Brenda'),
datos_entregable-# ('Andres');
INSERT 0 3
datos_entregable=# SELECT * FROM teacher;
 id | teacher
----+---------
  1 | Maria
  2 | Brenda
  3 | Andres
(3 filas)


datos_entregable=# INSERT INTO categories (category) VALUES
datos_entregable-# ('Programacion'),
datos_entregable-# ('Sofware'),
datos_entregable-# ('Diseño');
INSERT 0 3
datos_entregable=# SELECT * FROM categories;
 id |   category
----+--------------
  1 | Programacion
  2 | Sofware
  3 | Diseño
(3 filas)


datos_entregable=# INSERT INTO title (title) VALUES
datos_entregable-# ('Desarrollo de paginas Web'),
datos_entregable-# ('Desarrollo de Sofware'),
datos_entregable-# ('Diseño de Paginas');
INSERT 0 3
datos_entregable=# SELECT * FROM title;
 id |           title
----+---------------------------
  1 | Desarrollo de paginas Web
  2 | Desarrollo de Sofware
  3 | Diseño de Paginas
(3 filas)


datos_entregable=# INSERT INTO description (description) VALUES
datos_entregable-# ('Desarrolla tu propia Pagina Web'),
datos_entregable-# ('Desarrolla tu Programacion'),
datos_entregable-# ('Diseña tu pagina');
INSERT 0 3
datos_entregable=# SELECT * FROM description;
 id |           description
----+---------------------------------
  1 | Desarrolla tu propia Pagina Web
  2 | Desarrolla tu Programacion
  3 | Diseña tu pagina
(3 filas)


datos_entregable=# INSERT INTO course_videos (title , url) VALUES
datos_entregable-# (1 , 'https://FrontEnd'),
datos_entregable-# (2 , 'https://Sofware'),
datos_entregable-# (3 , 'https://Diseño');
INSERT 0 3
datos_entregable=# SELECT * FROM course_videos;
 id | title |       url
----+-------+------------------
  1 | 1     | https://FrontEnd
  2 | 2     | https://Sofware
  3 | 3     | https://Diseño
(3 filas)

datos_entregable=# INSERT INTO course_general (course_description , course_level , course_teacher, course_user, course_category, course_videos,course_title)VALUES
datos_entregable-# (1, 1 , 1 , 1, 1, 1, 1);
INSERT 0 1
datos_entregable=# SELECT * FROM course_general;
 id | course_description | course_level | course_teacher | course_user | course_category | course_videos | course_title
----+--------------------+--------------+----------------+-------------+-----------------+---------------+--------------
  1 |                  1 |            1 |              1 |           1 |               1 |             1 |            1
(1 fila)


datos_entregable=# INSERT INTO course_general (course_description , course_level , course_teacher, course_user, course_category, course_videos,course_title)VALUES
datos_entregable-# (2,2,3,4,2,2,2),
datos_entregable-# (3,3,2,1,3,3,3);
INSERT 0 2
datos_entregable=# SELECT * FROM course_general;
 id | course_description | course_level | course_teacher | course_user | course_category | course_videos | course_title
----+--------------------+--------------+----------------+-------------+-----------------+---------------+--------------
  1 |                  1 |            1 |              1 |           1 |               1 |             1 |            1
  2 |                  2 |            2 |              3 |           4 |               2 |             2 |            2
  3 |                  3 |            3 |              2 |           1 |               3 |             3 |            3
(3 filas)

datos_entregable=# SELECT course_general.id , course_title , course_description, level.level , users.name , categories.category , course_videos.title , course_videos.url , teacher.teacher , description.description FROM course_general JOIN level ON level.id = course_general.course_level JOIN users ON users.id=course_general.course_user JOIN categories ON categories.id = course_general.course_category JOIN course_videos ON course_videos.id=course_general.course_videos JOIN teacher ON teacher.id= course_general.course_teacher JOIN description ON description.id=course_general.course_description;
 id | course_title | course_description |    level     | name |   category   | title |       url        | teacher |           description
----+--------------+--------------------+--------------+------+--------------+-------+------------------+---------+---------------------------------
  1 |            1 |                  1 | Beginner     |    1 | Programacion | 1     | https://FrontEnd | Maria   | Desarrolla tu propia Pagina Web
  2 |            2 |                  2 | Intermediate |    4 | Sofware      | 2     | https://Sofware  | Andres  | Desarrolla tu Programacion
  3 |            3 |                  3 | Advance      |    1 | Diseño       | 3     | https://Diseño   | Brenda  | Diseña tu pagina
(3 filas)
